# Alertmanager Configuration
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@example.com'

# Templates for alert notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routing tree
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'market-agent-webhook'

# Receivers define where alerts are sent
receivers:
  - name: 'market-agent-webhook'
    webhook_configs:
      - url: 'http://market-programmer-agent:8001/webhook/alerts'
        send_resolved: true
        http_config:
          follow_redirects: true
        title: 'Alert from Prometheus'
        text: 'Alert: {{ .GroupLabels.alertname }}'

# Inhibition rules suppress alerts when other alerts are firing
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance'] 